# Use the base image for development
FROM etl_pipeline_base:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project into the container
COPY . .

# Install development-specific dependencies from requirements.txt
# This ensures all dependencies are present, including those for testing and local development
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the main pipeline script when the container starts
CMD ["python", "src/main.py"]