# Dockerfile_dev
# Extends Dockerfile_base for development purposes.

FROM base_etl_pipeline:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project into the container
# This includes source code, tests, docs, configs, etc.
COPY . .

# Command to run the main ETL pipeline script
# This will be the default command when the container starts
CMD ["python", "src/main.py"]