pipeline:
  name: local_csv_processing
  schedule: manual
  architecture: medallion
sources:
- name: input_csv_folder
  type: local_files
  format: ''
  mode: batch
  conn_secret: LOCAL_FILES_CONN
output:
  type: local_files
  conn_secret: LOCAL_FILES_CONN
pii_columns:
- customer_name
- email
