import duckdb
import pandas as pd
import os

def main():
    con = duckdb.connect(DB_PATH)

    # Ensure schemas exist
    con.execute("CREATE SCHEMA IF NOT EXISTS bronze;")
    con.execute("CREATE SCHEMA IF NOT EXISTS silver;")
    con.execute("CREATE SCHEMA IF NOT EXISTS gold;")
    con.execute("CREATE SCHEMA IF NOT EXISTS rejected;")

    # --- Setup: Create dummy silver tables for demonstration and testing ---
    # In a real pipeline, these would be generated by previous silver-layer transformations.
    # We'll create them here with some specific data to test rejection and tiering.

    # silver.customers_cleaned
    customers_data = {
        'customer_id': ['C1', 'C2', 'C3', 'C4', 'C5'],
        'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'david@example.com', 'eve@example.com'],
        'join_date': ['2023-01-01', '2023-01-05', '2023-01-10', '2023-01-15', '2023-01-20']
    }
    customers_df = pd.DataFrame(customers_data)
    con.execute("CREATE OR REPLACE TABLE silver.customers_cleaned AS SELECT * FROM customers_df;")

    # silver.transactions_cleaned
    # Include transactions for existing customers, a transaction for a non-existent customer,
    # and a transaction with a NULL customer_id to test rejection.
    transactions_data = {
        'transaction_id': ['T101', 'T102', 'T103', 'T104', 'T105', 'T106', 'T107', 'T108', 'T109', 'T110', 'T111', 'T112', 'T113'],
        'customer_id': ['C1', 'C1', 'C2', 'C2', 'C3', 'C3', 'C3', 'C4', 'C4', 'C5', 'C_NONEXISTENT', None, 'C1'], # C_NONEXISTENT and None for rejection
        'amount': [100.00, 200.00, 500.00, 600.00, 1000.00, 5000.00, 5000.00, 10000.00, 1000.00, 100.00, 75.00, 120.00, 15000.00], # C1 will have 15300 total
        'transaction_date': ['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13']
    }
    transactions_df = pd.DataFrame(transactions_data)
    con.execute("CREATE OR REPLACE TABLE silver.transactions_cleaned AS SELECT * FROM transactions_df;")

    # --- Transformation Logic ---

    # 1. Left-join transactions onto customers and identify rejected rows
    rejected_query = """
    WITH joined_data AS (
        SELECT
            t.transaction_id,
            t.customer_id AS original_transaction_customer_id,
            t.amount,
            t.transaction_date,
            c.customer_id AS matched_customer_id -- This will be NULL if no match
        FROM silver.transactions_cleaned AS t
        LEFT JOIN silver.customers_cleaned AS c
            ON t.customer_id = c.customer_id
    )
    SELECT
        transaction_id,
        original_transaction_customer_id,
        amount,
        transaction_date,
        'No matching customer_id or customer_id is NULL' AS rejection_reason
    FROM joined_data
    WHERE matched_customer_id IS NULL;
    """
    rejected_df = con.execute(rejected_query).fetchdf()

    if not rejected_df.empty:
        # Check if rejected.rejected_rows table exists
        table_exists = con.execute("SELECT count(*) FROM information_schema.tables WHERE table_schema = 'rejected' AND table_name = 'rejected_rows';").fetchone()[0] > 0

        if not table_exists:
            # Create table if it doesn't exist
            con.execute("""
                CREATE TABLE rejected.rejected_rows (
                    transaction_id VARCHAR,
                    original_transaction_customer_id VARCHAR,
                    amount DOUBLE, -- Use DOUBLE for amount to match pandas float64
                    transaction_date DATE,
                    rejection_reason VARCHAR
                );
            """)
        
        # Insert or append rejected rows
        con.execute("INSERT INTO rejected.rejected_rows SELECT * FROM rejected_df;")
    
    # 2. Process valid rows: aggregate, calculate, and assign spending tier
    gold_query = """
    WITH valid_transactions AS (
        SELECT
            c.customer_id,
            t.transaction_id,
            t.amount
        FROM silver.customers_cleaned AS c
        JOIN silver.transactions_cleaned AS t
            ON c.customer_id = t.customer_id
    ),
    aggregated_spending AS (
        SELECT
            customer_id,
            SUM(amount) AS total_spent,
            COUNT(transaction_id) AS transaction_count,
            SUM(amount) / COUNT(transaction_id) AS average_transaction_value
        FROM valid_transactions
        GROUP BY customer_id
    )
    SELECT
        customer_id,
        total_spent,
        transaction_count,
        average_transaction_value,
        CASE
            WHEN total_spent > 10000 THEN 'High'
            WHEN total_spent > 1000 THEN 'Medium'
            ELSE 'Low'
        END AS spending_tier
    FROM aggregated_spending;
    """
    
    customer_spending_df = con.execute(gold_query).fetchdf()

    # 3. Write result to GOLD as customer_spending
    con.execute("CREATE OR REPLACE TABLE gold.customer_spending AS SELECT * FROM customer_spending_df;")

    con.close()

if __name__ == "__main__":
    main()